### ISSUE TITLE
Topology Diagram Question

### ISSUE THREAD

**Issue by FuzzOli87** [kris-nova/kops-demo#1]
Great guide!

I have a question regarding your diagrams(as I'm trying to understand the topology) It looks like you have TWO bastion instances, or two of the same one. Yet, following your guide(albeit, I used smaller nodes) I only have ONE bastion instance created.

Am I reading your diagram correctly?

**Comment by krisnova** [comment]
Hey, so assuming you are talking about this diagram:

![image](https://cloud.githubusercontent.com/assets/13757818/24680590/bccee2f0-194e-11e7-8695-fb029c65d74d.png)

Basically what the diagram depicts (to me) is that the bastion instance group (which can be N number of bastions) can span the public subnets. In other words.. how ever many bastions you configure, they all should be able to get traffic into the private subnets.

By default, kops sets the size of the bastion instance group to **1** - hence why you are only seeing 1 bastion instance.

**Comment by krisnova** [comment]
Can I mark this as closed?

**Comment by krisnova** [comment]
@FuzzOli87 ping - Can I close this?

**Comment by FuzzOli87** [comment]
Yes! Thanks for answering my question.
