### ISSUE TITLE
Question on "this is bad" comment

### ISSUE THREAD

**Issue by StevenACoffman** [kris-nova/kops-demo#2]
Thank you for an awesome guide! I really appreciated it!

You have [this comment](https://github.com/kris-nova/kops-demo/blob/master/kubecfg-magic.sh#L6):
> This is bad, please do not do this in the wild.

Were you just talking about echoing the userid/password from the kube config, or did you also mean there was something bad about the dashboard install bits in that script?

**Comment by geojaz** [comment]
Installing the dashboard like that is just fine. 

I think the comment was initially because this comes from a live demo. During it, the root user and password would be spit out onto the console in front of the audience. Just be more careful with your creds. :)

**Comment by StevenACoffman** [comment]
Cool. I just wanted to check. Thanks!
